spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/school?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: mxy713914
    driver-class-name: com.mysql.cj.jdbc.Driver

